"""Add reports table

Revision ID: 68a3ed657017
Revises: 
Create Date: 2025-10-24 12:30:04.195931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a3ed657017'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('questions_count', sa.Integer(), nullable=True),
    sa.Column('answered_count', sa.Integer(), nullable=True),
    sa.Column('unanswered_count', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_minutes', sa.Float(), nullable=True),
    sa.Column('report_content', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_date', 'reports', ['chat_id', 'report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_date', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
